FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.dev.txt /app/
RUN python -m pip install --upgrade pip \
    && pip install --no-cache-dir -r /app/requirements.txt \
    && pip install --no-cache-dir -r /app/requirements.dev.txt

COPY ./ /app

CMD ["flask", "run", "--host=0.0.0.0"]
