version: "3.1"

services:
  python:
    build: ..
    user: root
    volumes:
      - ../:/app
    tty: true

  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
