import os
from dotenv import load_dotenv

load_dotenv()

DEBUG = os.getenv('DEBUG')
LINEBOT_CHANNEL_SECRET = os.getenv('LINEBOT_CHANNEL_SECRET')
LINEBOT_CHANNEL_ACCESS_TOKEN = os.getenv('LINEBOT_CHANNEL_ACCESS_TOKEN')
FIRESTORE_PROJECT_ID = os.getenv('FIRESTORE_PROJECT_ID')
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
SERVER_URL = os.getenv('SERVER_URL')
SERVER_ADMIN_LINE_USER_ID = os.getenv('SERVER_ADMIN_LINE_USER_ID')
LINE_ADD_FRIENDS_URL = os.getenv('LINE_ADD_FRIENDS_URL')
LINE_LOGIN_CHANNEL_ID = os.getenv('LINE_LOGIN_CHANNEL_ID')
LINE_LOGIN_CHANNEL_SECRET = os.getenv('LINE_LOGIN_CHANNEL_SECRET')
LINE_LOGIN_CALLBACK_URL = os.getenv('LINE_LOGIN_CALLBACK_URL')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4o-mini')
FLASK_SECRET_KEY = os.getenv('FLASK_SECRET_KEY', '')
API_KEY_ENCRYPTION_KEY = os.getenv('API_KEY_ENCRYPTION_KEY', '')
INTERNAL_API_KEY = os.getenv('INTERNAL_API_KEY', '')
FLASK_ENV = (os.getenv('FLASK_ENV') or '').lower()
IS_DEVELOPMENT = FLASK_ENV == 'development'
LOCAL_AUTH_USER_CODE = os.getenv('LOCAL_AUTH_USER_CODE', '')
LOCAL_AUTH_PASSWORD = os.getenv('LOCAL_AUTH_PASSWORD', '')
# 規約・プライバシーポリシーに表示する提供者名と問い合わせ導線。
# 無料βではハンドル名を既定とし、有料化時に特商法表記へ差し替える。
SERVICE_PROVIDER_NAME = os.getenv('SERVICE_PROVIDER_NAME', 'fezzlk')
CONTACT_FORM_URL = os.getenv('CONTACT_FORM_URL', '')
