import os
from dotenv import load_dotenv

load_dotenv()

DEBUG = os.getenv('DEBUG')
LINEBOT_CHANNEL_SECRET = os.getenv('LINEBOT_CHANNEL_SECRET')
LINEBOT_CHANNEL_ACCESS_TOKEN = os.getenv('LINEBOT_CHANNEL_ACCESS_TOKEN')
OPEN_WEATHER_MAP_API_KEY = os.getenv('OPEN_WEATHER_MAP_API_KEY')
MONGO_URI = os.getenv('MONGO_URI')
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
SERVER_URL = os.getenv('SERVER_URL')
SERVER_ADMIN_LINE_USER_ID = os.getenv('SERVER_ADMIN_LINE_USER_ID')
