import os
from dotenv import load_dotenv

load_dotenv()

DEBUG = os.getenv('DEBUG')
LINEBOT_CHANNEL_SECRET = os.getenv('LINEBOT_CHANNEL_SECRET')
LINEBOT_CHANNEL_ACCESS_TOKEN = os.getenv('LINEBOT_CHANNEL_ACCESS_TOKEN')
OPEN_WEATHER_MAP_API_KEY = os.getenv('OPEN_WEATHER_MAP_API_KEY')
FIRESTORE_PROJECT_ID = os.getenv('FIRESTORE_PROJECT_ID')
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
SERVER_URL = os.getenv('SERVER_URL')
SERVER_ADMIN_LINE_USER_ID = os.getenv('SERVER_ADMIN_LINE_USER_ID')
LINE_ADD_FRIENDS_URL = os.getenv('LINE_ADD_FRIENDS_URL')
LINE_LOGIN_CHANNEL_ID = os.getenv('LINE_LOGIN_CHANNEL_ID')
LINE_LOGIN_CHANNEL_SECRET = os.getenv('LINE_LOGIN_CHANNEL_SECRET')
LINE_LOGIN_CALLBACK_URL = os.getenv('LINE_LOGIN_CALLBACK_URL')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4o-mini')
FLASK_ENV = (os.getenv('FLASK_ENV') or '').lower()
IS_DEVELOPMENT = FLASK_ENV == 'development'
LOCAL_AUTH_USER_CODE = os.getenv('LOCAL_AUTH_USER_CODE', '')
LOCAL_AUTH_PASSWORD = os.getenv('LOCAL_AUTH_PASSWORD', '')
